#!/bin/sh
# -*- coding: utf-8 -*-
# Author: Pär Andersson  (National Supercomputer Centre, Sweden)
# Version: 0.3 2007-07-30
#

SCREENSESSION="$1"

# If DISPLAY is set then set that in the screen, then create a new
# window with that environment and kill the old one.
if [ "$DISPLAY" != "" ];then
    screen -S "$SCREENSESSION" -X unsetenv DISPLAY
    screen -S "$SCREENSESSION" -X setenv DISPLAY "$DISPLAY"
fi

screen -S "$SCREENSESSION" -X screen
screen -p1 -S "$SCREENSESSION" -X kill #META tab has outlived its usefulness
screen -S "$SCREENSESSION" -p0 -X exec clear 
screen -S "$SCREENSESSION" -rd
