#!/bin/bash

jobid=$1
jobnode=$2
user=$3

# check if this job is still running?
scontrol show job ${jobid} 2>&1 | grep JobState > /dev/null

if [ $? -ne 1 ]; then

  # Yep it is, so lets send mail

  subj="Your Interactive Job ${jobid} on ${jobnode}"
  msg="Your Interactive Job ${jobid} on ${jobnode} is finishing in 10 minutes

  You can extend the time for this job:
      # scontrol update job ${jobid} timelimit=<HH:MM:SS>

  And you can reconnect to this job by
      # ssh ${jobnode}
      # screen -r"

  echo "${msg}" | mail -s "${subj}" ${user}@usgs.gov

fi
